on: push
jobs:
  # label of the container job
  postgres-job:
    # containers must run in Linux based operating systems
    runs-on: ubuntu-latest
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: interviewee
      POSTGRES_PASSWORD: wannasucceed
      POSTGRES_DB: awesomeinc
    ports:
      - 5432:5432
	volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
      - data:/var/lib/postgresql/data
	  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: interviewee@test.com
      PGADMIN_DEFAULT_PASSWORD: wannasucceed
    volumes:
      - ./data/servers.json:/pgadmin4/servers.json
    ports:
      - 8080:80
    depends_on:
      - postgres
volumes:
  data: {}
