# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: interviewee
          POSTGRES_PASSWORD: wannasucceed
          POSTGRES_DB: awesomeinc
        volumes:
          - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
          - data:/var/lib/postgresql/data
        ports:
          - 5432:5432
      pgadmin:
        image: dpage/pgadmin4:6
        env:
          PGADMIN_DEFAULT_EMAIL: interviewee@test.com
          PGADMIN_DEFAULT_PASSWORD: wannasucceed
        volumes:
          - ./data/servers.json:/pgadmin4/servers.json
        ports:
          - 8080:80
        depends_on:
          - postgres
   volumes:
     data: {}
