on: push   
jobs:
  postgres-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: interviewee
          POSTGRES_PASSWORD: wannasucceed
          POSTGRES_DB: awesomeinc
        volumes:
          - /data/init.sql:/docker-entrypoint-initdb.d/init.sql
          - data:/var/lib/postgresql/data
        ports:
          - 5432:5432
    steps:
        run:
         pgadmin:
           image: dpage/pgadmin4
           env:
             PGADMIN_DEFAULT_EMAIL: interviewee@test.com
             PGADMIN_DEFAULT_PASSWORD: wannasucceed
           volumes:
             - /data/servers.json:/pgadmin4/servers.json
           ports:
             - 8080:80
           depends_on:
             - postgres
     volumes:
      data: {}
